### ISSUE TITLE
Migrate data from new H2 database to Postgres

### ISSUE THREAD

**Issue by pkutlunin** [gocd/gocd-database-migrator#6]
As part of migrating to GoCD 20.8.0 from 20.4.0, we had to migrate the DB: https://docs.gocd.org/current/installation/upgrade_to_gocd_20.5.0.html

We chose to migrate to H2 as a temporary solution but we would like to migrate the data to Postgres later on.
The migration process from H2 to H2 went smoothly but the migration from new H2 database to Postgres failed with multiple exceptions (see below):

Is there a plan to support migration from new H2 database to Postgres?

Migrator version: `1.0.0-33`.
Java: `openjdk version "11.0.7" 2020-04-14`

##### Exceptions
```
ERROR [pool-2-thread-1] DbSync:203 - null
org.jooq.exception.DataAccessException: SQL [select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ?]; Data conversion error converting "2006001_remove_data_sharing_settings_table"; SQL statement:
select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ? [22018-200]
	at org.jooq_3.13.1.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2751)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2690)
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:341)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "2006001_remove_data_sharing_settings_table"; SQL statement:
select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ? [22018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.Value.convertTo(Value.java:875)
	at org.h2.value.Value.convertTo(Value.java:758)
	at org.h2.value.Value.compareWithNull(Value.java:1583)
	at org.h2.engine.Database.compareWithNull(Database.java:427)
	at org.h2.expression.condition.Comparison.compare(Comparison.java:311)
	at org.h2.expression.condition.Comparison.getValue(Comparison.java:256)
	at org.h2.expression.Expression.getBooleanValue(Expression.java:258)
	at org.h2.command.dml.Select.isConditionMet(Select.java:448)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1846)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
	at org.h2.result.LazyResult.next(LazyResult.java:60)
	at org.h2.command.dml.Select.queryFlat(Select.java:737)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:844)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
	at org.h2.command.dml.Query.query(Query.java:489)
	at org.h2.command.dml.Query.query(Query.java:451)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:233)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3956)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	... 7 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "2006001_remove_data_sharing_settings_table"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.h2.value.Value.convertToLong(Value.java:1011)
	at org.h2.value.Value.convertTo(Value.java:808)
	... 31 common frames omitted
Exception in thread "pool-2-thread-1" java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ?]; Data conversion error converting "2006001_remove_data_sharing_settings_table"; SQL statement:
select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ? [22018-200]
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jooq.exception.DataAccessException: SQL [select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ?]; Data conversion error converting "2006001_remove_data_sharing_settings_table"; SQL statement:
select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ? [22018-200]
	at org.jooq_3.13.1.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2751)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:385)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:354)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2690)
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:341)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	... 3 more
Caused by: org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "2006001_remove_data_sharing_settings_table"; SQL statement:
select * from DATABASECHANGELOG where id > cast(? as bigint) order by id limit ? [22018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.value.Value.convertTo(Value.java:875)
	at org.h2.value.Value.convertTo(Value.java:758)
	at org.h2.value.Value.compareWithNull(Value.java:1583)
	at org.h2.engine.Database.compareWithNull(Database.java:427)
	at org.h2.expression.condition.Comparison.compare(Comparison.java:311)
	at org.h2.expression.condition.Comparison.getValue(Comparison.java:256)
	at org.h2.expression.Expression.getBooleanValue(Expression.java:258)
	at org.h2.command.dml.Select.isConditionMet(Select.java:448)
	at org.h2.command.dml.Select$LazyResultQueryFlat.fetchNextRow(Select.java:1846)
	at org.h2.result.LazyResult.hasNext(LazyResult.java:101)
	at org.h2.result.LazyResult.next(LazyResult.java:60)
	at org.h2.command.dml.Select.queryFlat(Select.java:737)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:844)
	at org.h2.command.dml.Query.queryWithoutCacheLazyCheck(Query.java:201)
	at org.h2.command.dml.Query.query(Query.java:489)
	at org.h2.command.dml.Query.query(Query.java:451)
	at org.h2.command.CommandContainer.query(CommandContainer.java:285)
	at org.h2.command.Command.executeQuery(Command.java:195)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:233)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3956)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:371)
	... 7 more
Caused by: java.lang.NumberFormatException: For input string: "2006001_remove_data_sharing_settings_table"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at org.h2.value.Value.convertToLong(Value.java:1011)
	at org.h2.value.Value.convertTo(Value.java:808)
	... 31 more
```
```
ERROR [pool-2-thread-2] DbSync:203 - null
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Exception in thread "pool-2-thread-2" java.lang.RuntimeException: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:204)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at com.thoughtworks.go.dbsync.DbSync.dumpTableSQL(DbSync.java:354)
	at com.thoughtworks.go.dbsync.DbSync.lambda$doExport$13(DbSync.java:201)
	... 3 more
```
```
INFO  [main] DbSync:121 - Done copying database records.
INFO  [main] DbSync:126 - Setting sequences for all tables.
ERROR [main] DbSync:87 - null
org.postgresql.util.PSQLException: ERROR: function setval(unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2313)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:331)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at com.thoughtworks.go.dbsync.Util.execute(Util.java:84)
	at com.thoughtworks.go.dbsync.Util.executeAndLog(Util.java:61)
	at com.thoughtworks.go.dbsync.DbSync.resetSequences(DbSync.java:310)
	at com.thoughtworks.go.dbsync.DbSync.lambda$export$7(DbSync.java:127)
	at com.thoughtworks.go.dbsync.Util.withDataSource(Util.java:97)
	at com.thoughtworks.go.dbsync.DbSync.lambda$export$11(DbSync.java:125)
	at com.thoughtworks.go.dbsync.DbSync.withWriter(DbSync.java:292)
	at com.thoughtworks.go.dbsync.DbSync.export(DbSync.java:101)
	at com.thoughtworks.go.dbsync.cli.Main.main(Main.java:46)
2020-10-08 10:37:52,200 ERROR [main] DbSync:99 - null
java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: function setval(unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
	at com.thoughtworks.go.dbsync.Util.execute(Util.java:88)
	at com.thoughtworks.go.dbsync.Util.executeAndLog(Util.java:61)
	at com.thoughtworks.go.dbsync.DbSync.resetSequences(DbSync.java:310)
	at com.thoughtworks.go.dbsync.DbSync.lambda$export$7(DbSync.java:127)
	at com.thoughtworks.go.dbsync.Util.withDataSource(Util.java:97)
	at com.thoughtworks.go.dbsync.DbSync.lambda$export$11(DbSync.java:125)
	at com.thoughtworks.go.dbsync.DbSync.withWriter(DbSync.java:292)
	at com.thoughtworks.go.dbsync.DbSync.export(DbSync.java:101)
	at com.thoughtworks.go.dbsync.cli.Main.main(Main.java:46)
Caused by: org.postgresql.util.PSQLException: ERROR: function setval(unknown, text) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2313)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:331)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at com.thoughtworks.go.dbsync.Util.execute(Util.java:84)
	... 8 common frames omitted
```

**Comment by maheshp** [comment]
@pkutlunin can you please try the migration using the [latest](https://github.com/gocd/gocd-database-migrator/releases/tag/1.0.0-39) version of the tool.

**Comment by pkutlunin** [comment]
> DbSync:163 - All good!

Now it works. @maheshp thank you for fixing it so quickly!
