### ISSUE TITLE
Db migrator fails for default username

### ISSUE THREAD

**Issue by sahlone** [gocd/gocd-database-migrator#9]
WHile running the db migrator for h2db to postgress db I get the below error.
I have verified the target database connection details using psql from the same machine as I am running the migrator from.
I am running below command and the output is listed. Not sure where is `go` user comming from
```
./bin/gocd-database-migrator --insert --progress --source-db-url='jdbc:h2:/godata/db/h2db/cruise' --source-db-user='sa' --source-db-password=''
 --target-db-url='jdbc:postgresql://gocd-database-1.eu-central-1.rds.amazonaws.com:5432/gocd'--target-db-user='xxxx' --target-db-password='xxxx'
INFO: No `--source-db-driver-class` is specified. Setting `--source-db-driver-class='org.h2.Driver'`.
INFO: No `--target-db-driver-class` specified. Setting `--target-db-driver-class='org.postgresql.Driver'`.
2021-01-25 13:04:33,331 INFO  [main] DbSync:77 - Using dialect H2 for source database.
2021-01-25 13:04:33,870 ERROR [main] DbSync:103 - null
java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "go")
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at com.thoughtworks.go.dbsync.Util.withDataSource(Util.java:95)
	at com.thoughtworks.go.dbsync.DbSync.export(DbSync.java:78)
	at com.thoughtworks.go.dbsync.cli.Main.main(Main.java:46)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "go"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:525)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:146)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.connect(Driver.java:261)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665)
	... 5 common frames omitted
java.lang.RuntimeException: java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "go")
	at com.thoughtworks.go.dbsync.Util.withDataSource(Util.java:104)
	at com.thoughtworks.go.dbsync.DbSync.export(DbSync.java:78)
	at com.thoughtworks.go.dbsync.cli.Main.main(Main.java:46)
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "go")
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at com.thoughtworks.go.dbsync.Util.withDataSource(Util.java:95)
	... 2 more
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "go"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:525)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:146)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.connect(Driver.java:261)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665)
	... 5 more
```

**Comment by arvindsv** [comment]
Not sure where "go" is coming from, but isn't there a missing space in your command-line before `--target-db-user='xxxx'` or is that just because of the way it is pasted?

**Comment by sahlone** [comment]
> Not sure where "go" is coming from, but isn't there a missing space in your command-line before `--target-db-user='xxxx'` or is that just because of the way it is pasted?

It was just copy paste issue
